//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormClient.LemonWayServiceReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "LemonWayServiceReference.ServicesSoap")]
    public interface ServicesSoap
    {

        // CODEGEN: Generating message contract since element name FibonacciResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/Fibonacci", ReplyAction = "*")]
        WindowsFormClient.LemonWayServiceReference.FibonacciResponse Fibonacci(WindowsFormClient.LemonWayServiceReference.FibonacciRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/Fibonacci", ReplyAction = "*")]
        System.Threading.Tasks.Task<WindowsFormClient.LemonWayServiceReference.FibonacciResponse> FibonacciAsync(WindowsFormClient.LemonWayServiceReference.FibonacciRequest request);

        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/XmlToJson", ReplyAction = "*")]
        WindowsFormClient.LemonWayServiceReference.XmlToJsonResponse XmlToJson(WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/XmlToJson", ReplyAction = "*")]
        System.Threading.Tasks.Task<WindowsFormClient.LemonWayServiceReference.XmlToJsonResponse> XmlToJsonAsync(WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class FibonacciRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Fibonacci", Namespace = "http://tempuri.org/", Order = 0)]
        public WindowsFormClient.LemonWayServiceReference.FibonacciRequestBody Body;

        public FibonacciRequest()
        {
        }

        public FibonacciRequest(WindowsFormClient.LemonWayServiceReference.FibonacciRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class FibonacciRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public int n;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int timeout;

        public FibonacciRequestBody()
        {
        }

        public FibonacciRequestBody(int n, int timeout)
        {
            this.n = n;
            this.timeout = timeout;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class FibonacciResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "FibonacciResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public WindowsFormClient.LemonWayServiceReference.FibonacciResponseBody Body;

        public FibonacciResponse()
        {
        }

        public FibonacciResponse(WindowsFormClient.LemonWayServiceReference.FibonacciResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class FibonacciResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string FibonacciResult;

        public FibonacciResponseBody()
        {
        }

        public FibonacciResponseBody(string FibonacciResult)
        {
            this.FibonacciResult = FibonacciResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class XmlToJsonRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "XmlToJson", Namespace = "http://tempuri.org/", Order = 0)]
        public WindowsFormClient.LemonWayServiceReference.XmlToJsonRequestBody Body;

        public XmlToJsonRequest()
        {
        }

        public XmlToJsonRequest(WindowsFormClient.LemonWayServiceReference.XmlToJsonRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class XmlToJsonRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string xml;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int timeout;

        public XmlToJsonRequestBody()
        {
        }

        public XmlToJsonRequestBody(string xml, int timeout)
        {
            this.xml = xml;
            this.timeout = timeout;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class XmlToJsonResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "XmlToJsonResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public WindowsFormClient.LemonWayServiceReference.XmlToJsonResponseBody Body;

        public XmlToJsonResponse()
        {
        }

        public XmlToJsonResponse(WindowsFormClient.LemonWayServiceReference.XmlToJsonResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class XmlToJsonResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string XmlToJsonResult;

        public XmlToJsonResponseBody()
        {
        }

        public XmlToJsonResponseBody(string XmlToJsonResult)
        {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : WindowsFormClient.LemonWayServiceReference.ServicesSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<WindowsFormClient.LemonWayServiceReference.ServicesSoap>, WindowsFormClient.LemonWayServiceReference.ServicesSoap
    {

        public ServicesSoapClient()
        {
        }

        public ServicesSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormClient.LemonWayServiceReference.FibonacciResponse WindowsFormClient.LemonWayServiceReference.ServicesSoap.Fibonacci(WindowsFormClient.LemonWayServiceReference.FibonacciRequest request)
        {
            return base.Channel.Fibonacci(request);
        }

        public string Fibonacci(int n, int timeout)
        {
            WindowsFormClient.LemonWayServiceReference.FibonacciRequest inValue = new WindowsFormClient.LemonWayServiceReference.FibonacciRequest();
            inValue.Body = new WindowsFormClient.LemonWayServiceReference.FibonacciRequestBody();
            inValue.Body.n = n;
            inValue.Body.timeout = timeout;
            WindowsFormClient.LemonWayServiceReference.FibonacciResponse retVal = ((WindowsFormClient.LemonWayServiceReference.ServicesSoap)(this)).Fibonacci(inValue);
            return retVal.Body.FibonacciResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormClient.LemonWayServiceReference.FibonacciResponse> WindowsFormClient.LemonWayServiceReference.ServicesSoap.FibonacciAsync(WindowsFormClient.LemonWayServiceReference.FibonacciRequest request)
        {
            return base.Channel.FibonacciAsync(request);
        }

        public System.Threading.Tasks.Task<WindowsFormClient.LemonWayServiceReference.FibonacciResponse> FibonacciAsync(int n, int timeout = 0)
        {
            WindowsFormClient.LemonWayServiceReference.FibonacciRequest inValue = new WindowsFormClient.LemonWayServiceReference.FibonacciRequest();
            inValue.Body = new WindowsFormClient.LemonWayServiceReference.FibonacciRequestBody();
            inValue.Body.n = n;
            inValue.Body.timeout = timeout;
            return ((WindowsFormClient.LemonWayServiceReference.ServicesSoap)(this)).FibonacciAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormClient.LemonWayServiceReference.XmlToJsonResponse WindowsFormClient.LemonWayServiceReference.ServicesSoap.XmlToJson(WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest request)
        {
            return base.Channel.XmlToJson(request);
        }

        public string XmlToJson(string xml, int timeout)
        {
            WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest inValue = new WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest();
            inValue.Body = new WindowsFormClient.LemonWayServiceReference.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.timeout = timeout;
            WindowsFormClient.LemonWayServiceReference.XmlToJsonResponse retVal = ((WindowsFormClient.LemonWayServiceReference.ServicesSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormClient.LemonWayServiceReference.XmlToJsonResponse> WindowsFormClient.LemonWayServiceReference.ServicesSoap.XmlToJsonAsync(WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest request)
        {
            return base.Channel.XmlToJsonAsync(request);
        }

        public System.Threading.Tasks.Task<WindowsFormClient.LemonWayServiceReference.XmlToJsonResponse> XmlToJsonAsync(string xml, int timeout = 0)
        {
            WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest inValue = new WindowsFormClient.LemonWayServiceReference.XmlToJsonRequest();
            inValue.Body = new WindowsFormClient.LemonWayServiceReference.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.timeout = timeout;
            return ((WindowsFormClient.LemonWayServiceReference.ServicesSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
